#!/bin/bash

# Setting up environment variables
# Add more configurations as needed
export FLASK_APP=app_run.py
export FLASK_ENV=development
export FLASK_DEBUG=1
export DATABASE_URL=sqlite:///default.db

echo "Environment variables set."

# Database operations
flask db init
flask db migrate -m "initial migration"
flask db upgrade

if [ $? -ne 0 ]; then
    echo "Database migration failed"
    exit 1
else
    echo "Database initialized and migrated."
fi

# Run Flask shell to execute initialization
python create_initial_data.py

if [ $? -eq 0 ]; then
    echo "Initial users created successfully."
else
    echo "Failed to create initial users"
    exit 1
fi

# Starting the Flask application
flask run

if [ $? -ne 0 ]; then
    echo "Failed to start Flask application"
    exit 1
fi
