"""empty message

Revision ID: 06ca69929d00
Revises: 19a75aa94ee4
Create Date: 2024-08-25 19:04:04.716914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ca69929d00'
down_revision = '19a75aa94ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('livemode', sa.Boolean(), nullable=True),
    sa.Column('product_metadata', sa.JSON(), nullable=True),
    sa.Column('package_dimensions', sa.JSON(), nullable=True),
    sa.Column('shippable', sa.Boolean(), nullable=True),
    sa.Column('statement_descriptor', sa.String(length=22), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit_label', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('stripe_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('unit_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('recurring', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('billing_scheme', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tiers', sa.JSON(), nullable=True),
    sa.Column('tiers_mode', sa.String(length=50), nullable=True),
    sa.Column('transform_quantity', sa.JSON(), nullable=True),
    sa.Column('lookup_key', sa.String(length=255), nullable=True),
    sa.Column('price_metadata', sa.JSON(), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['stripe_products.product_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_id')
    )
    op.create_table('stripe_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('price_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['stripe_prices.price_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_subscriptions')
    op.drop_table('stripe_prices')
    op.drop_table('stripe_products')
    # ### end Alembic commands ###
