"""current user mixin

Revision ID: 6557ce67a498
Revises: 972d648b0b28
Create Date: 2024-08-27 11:22:57.114735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6557ce67a498'
down_revision = '972d648b0b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_email', type_='foreignkey')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_foreign_key('fk_user_email', 'user', ['user_email'], ['email'])

    # ### end Alembic commands ###
