"""remove user email constraint

Revision ID: dcc78f3d9a9c
Revises: ef464c1c2630
Create Date: 2024-08-28 00:22:01.410831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc78f3d9a9c'
down_revision = 'ef464c1c2630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.drop_constraint('fk_user_email', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_email', 'user', ['user_email'], ['email'], ondelete='CASCADE')
        batch_op.alter_column('user_email',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
