"""update user email constraint

Revision ID: ef464c1c2630
Revises: 6557ce67a498
Create Date: 2024-08-27 19:06:23.795352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef464c1c2630'
down_revision = '6557ce67a498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=True))
        batch_op.create_foreign_key('fk_user_email', 'user', ['user_email'], ['email'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_email', type_='foreignkey')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
